In [2]:
import pandas as pd
df = pd.read_csv('D:/PythonDataAnliticsFiles/ReadyDataFrames/SalesData_1/CompleteDataFrame.csv')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371 entries, 0 to 370
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           371 non-null    str
 1   Product_Category  371 non-null    str
 2   Sub_Category      371 non-null    str
 3   Age_Group         371 non-null    str
 4   Total_Revenue     371 non-null    int64
 5   Total_Cost        371 non-null    int64
 6   Total_Profit      371 non-null    int64
 7   Avg_Revenue       371 non-null    int64
 8   Avg_Cost          371 non-null    int64
 9   Avg_Profit        371 non-null    int64
 10  Total_Orders      371 non-null    int64
 11  ROI               371 non-null    float64
dtypes: float64(1), int64(7), str(4)
memory usage: 34.9 KB

In [16]:
df.describe()

,Total_Revenue,Total_Cost,Total_Profit,Avg_Revenue,Avg_Cost,Avg_Profit,Total_Orders,ROI
count,3.710000e+02,3.710000e+02,3.710000e+02,371.000000,371.000000,371.000000,371.000000,371.000000
mean,2.298410e+05,1.429917e+05,8.684933e+04,762.762803,431.245283,331.536388,3626.188679,1.131833
std,5.992246e+05,4.079339e+05,1.990557e+05,804.305635,540.331827,298.941359,8535.498455,0.520347
min,8.000000e+00,4.000000e+00,4.000000e+00,4.000000,2.000000,2.000000,2.000000,0.020000
25%,9.186000e+03,3.776500e+03,4.149500e+03,141.500000,78.500000,77.000000,185.500000,0.595000
50%,3.636600e+04,1.548000e+04,1.618300e+04,512.000000,206.000000,231.000000,741.000000,1.320000
75%,1.595850e+05,7.992850e+04,6.567250e+04,910.000000,445.500000,516.500000,2984.500000,1.535000
max,5.818155e+06,3.967604e+06,1.850551e+06,4691.000000,3110.000000,1732.000000,100144.000000,1.970000

In [15]:
df.head()

,Country,Product_Category,Sub_Category,Age_Group,Total_Revenue,Total_Cost,Total_Profit,Avg_Revenue,Avg_Cost,Avg_Profit,Total_Orders,ROI
0,United States,Bikes,Road Bikes,Adults (35-64),5818155,3967604,1850551,2696,1839,858,3216,0.47
1,United States,Bikes,Mountain Bikes,Adults (35-64),4027310,2429911,1597399,2383,1438,945,2213,0.66
2,Australia,Bikes,Road Bikes,Adults (35-64),4496908,3328401,1168507,2342,1734,609,2798,0.35
3,United States,Bikes,Mountain Bikes,Young Adults (25-34),2556699,1547909,1008790,2412,1460,952,1434,0.65
4,United States,Bikes,Road Bikes,Young Adults (25-34),2990474,2011177,979297,2484,1670,813,1756,0.49

In [14]:
df.tail()

,Country,Product_Category,Sub_Category,Age_Group,Total_Revenue,Total_Cost,Total_Profit,Avg_Revenue,Avg_Cost,Avg_Profit,Total_Orders,ROI
366,France,Clothing,Caps,Seniors (64+),565,497,68,141,124,17,71,0.14
367,Germany,Clothing,Shorts,Youth (<25),114,52,62,57,26,31,2,1.19
368,Canada,Clothing,Caps,Seniors (64+),98,77,21,49,39,11,11,0.27
369,Australia,Clothing,Jerseys,Seniors (64+),512,504,8,256,252,4,12,0.02
370,Australia,Accessories,Bottles and Cages,Seniors (64+),8,4,4,4,2,2,2,1.00

In [ ]:
df.drop_duplicates(inplace=True)
df.isnull().sum()

Country             0
Product_Category    0
Sub_Category        0
Age_Group           0
Total_Revenue       0
Total_Cost          0
Total_Profit        0
Avg_Revenue         0
Avg_Cost            0
Avg_Profit          0
Total_Orders        0
ROI                 0
dtype: int64

In [ ]:
df['Margin'] = round(df['Total_Profit'] / df['Total_Revenue'], 2)

In [8]:
round(df.corr(numeric_only=True), 3)

,Total_Revenue,Total_Cost,Total_Profit,Avg_Revenue,Avg_Cost,Avg_Profit,Total_Orders,ROI,Margin
Total_Revenue,1.000,0.994,0.974,0.540,0.579,0.407,0.076,-0.326,-0.266
Total_Cost,0.994,1.000,0.942,0.541,0.588,0.392,0.026,-0.354,-0.300
Total_Profit,0.974,0.942,1.000,0.518,0.538,0.422,0.174,-0.254,-0.188
Avg_Revenue,0.540,0.541,0.518,1.000,0.977,0.924,-0.233,-0.434,-0.332
Avg_Cost,0.579,0.588,0.538,0.977,1.000,0.822,-0.204,-0.559,-0.465
Avg_Profit,0.407,0.392,0.422,0.924,0.822,1.000,-0.259,-0.156,-0.052
Total_Orders,0.076,0.026,0.174,-0.233,-0.204,-0.259,1.000,0.089,0.089
ROI,-0.326,-0.354,-0.254,-0.434,-0.559,-0.156,0.089,1.000,0.977
Margin,-0.266,-0.300,-0.188,-0.332,-0.465,-0.052,0.089,0.977,1.000

In [74]:
df.to_csv('D:/PythonDataAnliticsFiles/ReadyDataFrames/SalesData_1/CompleteDataFrame_PandasBuild.csv')